# RTC configuration for SRS
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8088;
    dir             ./objs/nginx/html;
}

rtc_server {
    enabled         on;
    listen          8000; # UDP port
    candidate       47.107.33.154;
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
    }
    
    dvr {
        enabled     on;
        dvr_path    ./objs/nginx/html/index/dvr/[app]/[stream]/[timestamp].mp4;
        dvr_plan    session;
    }
}
